// ==================== AUTH CONSTANTS ====================
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const PAYMENT_SUCCESS_REQUEST = 'PAYMENT_SUCCESS_REQUEST';
export const PAYMENT_SUCCESS_SUCCESS = 'PAYMENT_SUCCESS_SUCCESS';
export const PAYMENT_SUCCESS_FAIL = 'PAYMENT_SUCCESS_FAIL';
export const PAYMENT_SUCCESS_RESET = "PAYMENT_SUCCESS_RESET"

// ==================== USER MANAGEMENT CONSTANTS ====================
export const ALL_USER_REQUEST = 'ALL_USER_REQUEST';
export const ALL_USER_SUCCESS = 'ALL_USER_SUCCESS';
export const ALL_USER_FAIL = 'ALL_USER_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_RESET = 'DELETE_USER_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';

export const USER_STATS_REQUEST = 'USER_STATS_REQUEST';
export const USER_STATS_SUCCESS = 'USER_STATS_SUCCESS';
export const USER_STATS_FAIL = 'USER_STATS_FAIL';

// ==================== ROLE CONSTANTS ====================
export const ALL_ROLES_REQUEST = 'ALL_ROLES_REQUEST';
export const ALL_ROLES_SUCCESS = 'ALL_ROLES_SUCCESS';
export const ALL_ROLES_FAIL = 'ALL_ROLES_FAIL';

export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAIL = 'CREATE_ROLE_FAIL';
export const CREATE_ROLE_RESET = 'CREATE_ROLE_RESET';

export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAIL = 'DELETE_ROLE_FAIL';
export const DELETE_ROLE_RESET = 'DELETE_ROLE_RESET';

export const ALL_PERMISSIONS_REQUEST = 'ALL_PERMISSIONS_REQUEST';
export const ALL_PERMISSIONS_SUCCESS = 'ALL_PERMISSIONS_SUCCESS';
export const ALL_PERMISSIONS_FAIL = 'ALL_PERMISSIONS_FAIL';

// ==================== PRODUCT CONSTANTS ====================
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET';

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';

export const ADD_STOCK_REQUEST = 'ADD_STOCK_REQUEST';
export const ADD_STOCK_SUCCESS = 'ADD_STOCK_SUCCESS';
export const ADD_STOCK_FAIL = 'ADD_STOCK_FAIL';
export const ADD_STOCK_RESET = 'ADD_STOCK_RESET';

// ==================== WAREHOUSE CONSTANTS ====================
export const CREATE_WAREHOUSE_REQUEST = 'CREATE_WAREHOUSE_REQUEST';
export const CREATE_WAREHOUSE_SUCCESS = 'CREATE_WAREHOUSE_SUCCESS';
export const CREATE_WAREHOUSE_FAIL = 'CREATE_WAREHOUSE_FAIL';
export const CREATE_WAREHOUSE_RESET = 'CREATE_WAREHOUSE_RESET';

export const ALL_WAREHOUSES_REQUEST = 'ALL_WAREHOUSES_REQUEST';
export const ALL_WAREHOUSES_SUCCESS = 'ALL_WAREHOUSES_SUCCESS';
export const ALL_WAREHOUSES_FAIL = 'ALL_WAREHOUSES_FAIL';

export const WAREHOUSE_DETAILS_REQUEST = 'WAREHOUSE_DETAILS_REQUEST';
export const WAREHOUSE_DETAILS_SUCCESS = 'WAREHOUSE_DETAILS_SUCCESS';
export const WAREHOUSE_DETAILS_FAIL = 'WAREHOUSE_DETAILS_FAIL';

export const UPDATE_WAREHOUSE_REQUEST = 'UPDATE_WAREHOUSE_REQUEST';
export const UPDATE_WAREHOUSE_SUCCESS = 'UPDATE_WAREHOUSE_SUCCESS';
export const UPDATE_WAREHOUSE_FAIL = 'UPDATE_WAREHOUSE_FAIL';
export const UPDATE_WAREHOUSE_RESET = 'UPDATE_WAREHOUSE_RESET';

export const DELETE_WAREHOUSE_REQUEST = 'DELETE_WAREHOUSE_REQUEST';
export const DELETE_WAREHOUSE_SUCCESS = 'DELETE_WAREHOUSE_SUCCESS';
export const DELETE_WAREHOUSE_FAIL = 'DELETE_WAREHOUSE_FAIL';
export const DELETE_WAREHOUSE_RESET = 'DELETE_WAREHOUSE_RESET';

export const TRANSFER_STOCK_REQUEST = 'TRANSFER_STOCK_REQUEST';
export const TRANSFER_STOCK_SUCCESS = 'TRANSFER_STOCK_SUCCESS';
export const TRANSFER_STOCK_FAIL = 'TRANSFER_STOCK_FAIL';
export const TRANSFER_STOCK_RESET = 'TRANSFER_STOCK_RESET';

export const ALL_TRANSFERS_REQUEST = 'ALL_TRANSFERS_REQUEST';
export const ALL_TRANSFERS_SUCCESS = 'ALL_TRANSFERS_SUCCESS';
export const ALL_TRANSFERS_FAIL = 'ALL_TRANSFERS_FAIL';

// ==================== SUPPLIER CONSTANTS ====================
export const CREATE_SUPPLIER_REQUEST = 'CREATE_SUPPLIER_REQUEST';
export const CREATE_SUPPLIER_SUCCESS = 'CREATE_SUPPLIER_SUCCESS';
export const CREATE_SUPPLIER_FAIL = 'CREATE_SUPPLIER_FAIL';
export const CREATE_SUPPLIER_RESET = 'CREATE_SUPPLIER_RESET';

export const ALL_SUPPLIERS_REQUEST = 'ALL_SUPPLIERS_REQUEST';
export const ALL_SUPPLIERS_SUCCESS = 'ALL_SUPPLIERS_SUCCESS';
export const ALL_SUPPLIERS_FAIL = 'ALL_SUPPLIERS_FAIL';

export const SUPPLIER_DETAILS_REQUEST = 'SUPPLIER_DETAILS_REQUEST';
export const SUPPLIER_DETAILS_SUCCESS = 'SUPPLIER_DETAILS_SUCCESS';
export const SUPPLIER_DETAILS_FAIL = 'SUPPLIER_DETAILS_FAIL';

export const UPDATE_SUPPLIER_REQUEST = 'UPDATE_SUPPLIER_REQUEST';
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAIL = 'UPDATE_SUPPLIER_FAIL';
export const UPDATE_SUPPLIER_RESET = 'UPDATE_SUPPLIER_RESET';

export const DELETE_SUPPLIER_REQUEST = 'DELETE_SUPPLIER_REQUEST';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_FAIL = 'DELETE_SUPPLIER_FAIL';
export const DELETE_SUPPLIER_RESET = 'DELETE_SUPPLIER_RESET';

// ==================== PURCHASE ORDER CONSTANTS ====================
export const CREATE_PURCHASE_ORDER_REQUEST = 'CREATE_PURCHASE_ORDER_REQUEST';
export const CREATE_PURCHASE_ORDER_SUCCESS = 'CREATE_PURCHASE_ORDER_SUCCESS';
export const CREATE_PURCHASE_ORDER_FAIL = 'CREATE_PURCHASE_ORDER_FAIL';
export const CREATE_PURCHASE_ORDER_RESET = 'CREATE_PURCHASE_ORDER_RESET';

export const ALL_PURCHASE_ORDERS_REQUEST = 'ALL_PURCHASE_ORDERS_REQUEST';
export const ALL_PURCHASE_ORDERS_SUCCESS = 'ALL_PURCHASE_ORDERS_SUCCESS';
export const ALL_PURCHASE_ORDERS_FAIL = 'ALL_PURCHASE_ORDERS_FAIL';

export const PURCHASE_ORDER_DETAILS_REQUEST = 'PURCHASE_ORDER_DETAILS_REQUEST';
export const PURCHASE_ORDER_DETAILS_SUCCESS = 'PURCHASE_ORDER_DETAILS_SUCCESS';
export const PURCHASE_ORDER_DETAILS_FAIL = 'PURCHASE_ORDER_DETAILS_FAIL';

export const RECEIVE_STOCK_REQUEST = 'RECEIVE_STOCK_REQUEST';
export const RECEIVE_STOCK_SUCCESS = 'RECEIVE_STOCK_SUCCESS';
export const RECEIVE_STOCK_FAIL = 'RECEIVE_STOCK_FAIL';
export const RECEIVE_STOCK_RESET = 'RECEIVE_STOCK_RESET';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';
export const UPDATE_ORDER_STATUS_RESET = 'UPDATE_ORDER_STATUS_RESET';

// ==================== SALE CONSTANTS ====================
export const CREATE_SALE_REQUEST = 'CREATE_SALE_REQUEST';
export const CREATE_SALE_SUCCESS = 'CREATE_SALE_SUCCESS';
export const CREATE_SALE_FAIL = 'CREATE_SALE_FAIL';
export const CREATE_SALE_RESET = 'CREATE_SALE_RESET';

export const ALL_SALES_REQUEST = 'ALL_SALES_REQUEST';
export const ALL_SALES_SUCCESS = 'ALL_SALES_SUCCESS';
export const ALL_SALES_FAIL = 'ALL_SALES_FAIL';

export const SALE_DETAILS_REQUEST = 'SALE_DETAILS_REQUEST';
export const SALE_DETAILS_SUCCESS = 'SALE_DETAILS_SUCCESS';
export const SALE_DETAILS_FAIL = 'SALE_DETAILS_FAIL';

export const DAILY_SALES_SUMMARY_REQUEST = 'DAILY_SALES_SUMMARY_REQUEST';
export const DAILY_SALES_SUMMARY_SUCCESS = 'DAILY_SALES_SUMMARY_SUCCESS';
export const DAILY_SALES_SUMMARY_FAIL = 'DAILY_SALES_SUMMARY_FAIL';

// ==================== LEDGER CONSTANTS ====================
export const CREATE_LEDGER_ENTRY_REQUEST = 'CREATE_LEDGER_ENTRY_REQUEST';
export const CREATE_LEDGER_ENTRY_SUCCESS = 'CREATE_LEDGER_ENTRY_SUCCESS';
export const CREATE_LEDGER_ENTRY_FAIL = 'CREATE_LEDGER_ENTRY_FAIL';
export const CREATE_LEDGER_ENTRY_RESET = 'CREATE_LEDGER_ENTRY_RESET';

export const ALL_LEDGER_ENTRIES_REQUEST = 'ALL_LEDGER_ENTRIES_REQUEST';
export const ALL_LEDGER_ENTRIES_SUCCESS = 'ALL_LEDGER_ENTRIES_SUCCESS';
export const ALL_LEDGER_ENTRIES_FAIL = 'ALL_LEDGER_ENTRIES_FAIL';

export const LEDGER_ENTRY_DETAILS_REQUEST = 'LEDGER_ENTRY_DETAILS_REQUEST';
export const LEDGER_ENTRY_DETAILS_SUCCESS = 'LEDGER_ENTRY_DETAILS_SUCCESS';
export const LEDGER_ENTRY_DETAILS_FAIL = 'LEDGER_ENTRY_DETAILS_FAIL';

export const UPDATE_LEDGER_ENTRY_REQUEST = 'UPDATE_LEDGER_ENTRY_REQUEST';
export const UPDATE_LEDGER_ENTRY_SUCCESS = 'UPDATE_LEDGER_ENTRY_SUCCESS';
export const UPDATE_LEDGER_ENTRY_FAIL = 'UPDATE_LEDGER_ENTRY_FAIL';
export const UPDATE_LEDGER_ENTRY_RESET = 'UPDATE_LEDGER_ENTRY_RESET';

export const DELETE_LEDGER_ENTRY_REQUEST = 'DELETE_LEDGER_ENTRY_REQUEST';
export const DELETE_LEDGER_ENTRY_SUCCESS = 'DELETE_LEDGER_ENTRY_SUCCESS';
export const DELETE_LEDGER_ENTRY_FAIL = 'DELETE_LEDGER_ENTRY_FAIL';
export const DELETE_LEDGER_ENTRY_RESET = 'DELETE_LEDGER_ENTRY_RESET';

export const LEDGER_STATS_REQUEST = 'LEDGER_STATS_REQUEST';
export const LEDGER_STATS_SUCCESS = 'LEDGER_STATS_SUCCESS';
export const LEDGER_STATS_FAIL = 'LEDGER_STATS_FAIL';

// ==================== DAILY RECORD CONSTANTS ====================
export const CREATE_DAILY_RECORD_REQUEST = 'CREATE_DAILY_RECORD_REQUEST';
export const CREATE_DAILY_RECORD_SUCCESS = 'CREATE_DAILY_RECORD_SUCCESS';
export const CREATE_DAILY_RECORD_FAIL = 'CREATE_DAILY_RECORD_FAIL';
export const CREATE_DAILY_RECORD_RESET = 'CREATE_DAILY_RECORD_RESET';

export const ALL_DAILY_RECORDS_REQUEST = 'ALL_DAILY_RECORDS_REQUEST';
export const ALL_DAILY_RECORDS_SUCCESS = 'ALL_DAILY_RECORDS_SUCCESS';
export const ALL_DAILY_RECORDS_FAIL = 'ALL_DAILY_RECORDS_FAIL';

export const DAILY_RECORD_DETAILS_REQUEST = 'DAILY_RECORD_DETAILS_REQUEST';
export const DAILY_RECORD_DETAILS_SUCCESS = 'DAILY_RECORD_DETAILS_SUCCESS';
export const DAILY_RECORD_DETAILS_FAIL = 'DAILY_RECORD_DETAILS_FAIL';

export const UPDATE_DAILY_RECORD_REQUEST = 'UPDATE_DAILY_RECORD_REQUEST';
export const UPDATE_DAILY_RECORD_SUCCESS = 'UPDATE_DAILY_RECORD_SUCCESS';
export const UPDATE_DAILY_RECORD_FAIL = 'UPDATE_DAILY_RECORD_FAIL';
export const UPDATE_DAILY_RECORD_RESET = 'UPDATE_DAILY_RECORD_RESET';

export const DELETE_DAILY_RECORD_REQUEST = 'DELETE_DAILY_RECORD_REQUEST';
export const DELETE_DAILY_RECORD_SUCCESS = 'DELETE_DAILY_RECORD_SUCCESS';
export const DELETE_DAILY_RECORD_FAIL = 'DELETE_DAILY_RECORD_FAIL';
export const DELETE_DAILY_RECORD_RESET = 'DELETE_DAILY_RECORD_RESET';

export const DAILY_RECORD_STATS_REQUEST = 'DAILY_RECORD_STATS_REQUEST';
export const DAILY_RECORD_STATS_SUCCESS = 'DAILY_RECORD_STATS_SUCCESS';
export const DAILY_RECORD_STATS_FAIL = 'DAILY_RECORD_STATS_FAIL';

// ==================== CUSTOMER TRANSACTION CONSTANTS ====================
export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL';
export const CREATE_TRANSACTION_RESET = 'CREATE_TRANSACTION_RESET';

export const ALL_TRANSACTIONS_REQUEST = 'ALL_TRANSACTIONS_REQUEST';
export const ALL_TRANSACTIONS_SUCCESS = 'ALL_TRANSACTIONS_SUCCESS';
export const ALL_TRANSACTIONS_FAIL = 'ALL_TRANSACTIONS_FAIL';

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST';
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS';
export const TRANSACTION_DETAILS_FAIL = 'TRANSACTION_DETAILS_FAIL';

export const UPDATE_TRANSACTION_REQUEST = 'UPDATE_TRANSACTION_REQUEST';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAIL = 'UPDATE_TRANSACTION_FAIL';
export const UPDATE_TRANSACTION_RESET = 'UPDATE_TRANSACTION_RESET';

export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAIL = 'DELETE_TRANSACTION_FAIL';
export const DELETE_TRANSACTION_RESET = 'DELETE_TRANSACTION_RESET';

export const TRANSACTION_STATS_REQUEST = 'TRANSACTION_STATS_REQUEST';
export const TRANSACTION_STATS_SUCCESS = 'TRANSACTION_STATS_SUCCESS';
export const TRANSACTION_STATS_FAIL = 'TRANSACTION_STATS_FAIL';

// ==================== EXPENSE CONSTANTS ====================
export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_FAIL = 'CREATE_EXPENSE_FAIL';
export const CREATE_EXPENSE_RESET = 'CREATE_EXPENSE_RESET';

export const ALL_EXPENSES_REQUEST = 'ALL_EXPENSES_REQUEST';
export const ALL_EXPENSES_SUCCESS = 'ALL_EXPENSES_SUCCESS';
export const ALL_EXPENSES_FAIL = 'ALL_EXPENSES_FAIL';

export const EXPENSE_DETAILS_REQUEST = 'EXPENSE_DETAILS_REQUEST';
export const EXPENSE_DETAILS_SUCCESS = 'EXPENSE_DETAILS_SUCCESS';
export const EXPENSE_DETAILS_FAIL = 'EXPENSE_DETAILS_FAIL';

export const UPDATE_EXPENSE_REQUEST = 'UPDATE_EXPENSE_REQUEST';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';
export const UPDATE_EXPENSE_FAIL = 'UPDATE_EXPENSE_FAIL';
export const UPDATE_EXPENSE_RESET = 'UPDATE_EXPENSE_RESET';

export const DELETE_EXPENSE_REQUEST = 'DELETE_EXPENSE_REQUEST';
export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_FAIL = 'DELETE_EXPENSE_FAIL';
export const DELETE_EXPENSE_RESET = 'DELETE_EXPENSE_RESET';

// ==================== REPORT CONSTANTS ====================
export const SALES_REPORT_REQUEST = 'SALES_REPORT_REQUEST';
export const SALES_REPORT_SUCCESS = 'SALES_REPORT_SUCCESS';
export const SALES_REPORT_FAIL = 'SALES_REPORT_FAIL';

export const PROFIT_LOSS_REPORT_REQUEST = 'PROFIT_LOSS_REPORT_REQUEST';
export const PROFIT_LOSS_REPORT_SUCCESS = 'PROFIT_LOSS_REPORT_SUCCESS';
export const PROFIT_LOSS_REPORT_FAIL = 'PROFIT_LOSS_REPORT_FAIL';

export const EXPENSE_REPORT_REQUEST = 'EXPENSE_REPORT_REQUEST';
export const EXPENSE_REPORT_SUCCESS = 'EXPENSE_REPORT_SUCCESS';
export const EXPENSE_REPORT_FAIL = 'EXPENSE_REPORT_FAIL';

export const DISCOUNT_REPORT_REQUEST = 'DISCOUNT_REPORT_REQUEST';
export const DISCOUNT_REPORT_SUCCESS = 'DISCOUNT_REPORT_SUCCESS';
export const DISCOUNT_REPORT_FAIL = 'DISCOUNT_REPORT_FAIL';





// ==================== PAYMENT PROOF CONSTANTS ====================
export const SUBMIT_PAYMENT_PROOF_REQUEST = 'SUBMIT_PAYMENT_PROOF_REQUEST';
export const SUBMIT_PAYMENT_PROOF_SUCCESS = 'SUBMIT_PAYMENT_PROOF_SUCCESS';
export const SUBMIT_PAYMENT_PROOF_FAIL = 'SUBMIT_PAYMENT_PROOF_FAIL';
export const SUBMIT_PAYMENT_PROOF_RESET = 'SUBMIT_PAYMENT_PROOF_RESET';

export const GET_PENDING_PAYMENTS_REQUEST = 'GET_PENDING_PAYMENTS_REQUEST';
export const GET_PENDING_PAYMENTS_SUCCESS = 'GET_PENDING_PAYMENTS_SUCCESS';
export const GET_PENDING_PAYMENTS_FAIL = 'GET_PENDING_PAYMENTS_FAIL';

export const GET_ALL_PAYMENT_PROOFS_REQUEST = 'GET_ALL_PAYMENT_PROOFS_REQUEST';
export const GET_ALL_PAYMENT_PROOFS_SUCCESS = 'GET_ALL_PAYMENT_PROOFS_SUCCESS';
export const GET_ALL_PAYMENT_PROOFS_FAIL = 'GET_ALL_PAYMENT_PROOFS_FAIL';

export const APPROVE_PAYMENT_REQUEST = 'APPROVE_PAYMENT_REQUEST';
export const APPROVE_PAYMENT_SUCCESS = 'APPROVE_PAYMENT_SUCCESS';
export const APPROVE_PAYMENT_FAIL = 'APPROVE_PAYMENT_FAIL';
export const APPROVE_PAYMENT_RESET = 'APPROVE_PAYMENT_RESET';

export const DENY_PAYMENT_REQUEST = 'DENY_PAYMENT_REQUEST';
export const DENY_PAYMENT_SUCCESS = 'DENY_PAYMENT_SUCCESS';
export const DENY_PAYMENT_FAIL = 'DENY_PAYMENT_FAIL';
export const DENY_PAYMENT_RESET = 'DENY_PAYMENT_RESET';

export const GET_MY_PAYMENT_STATUS_REQUEST = 'GET_MY_PAYMENT_STATUS_REQUEST';
export const GET_MY_PAYMENT_STATUS_SUCCESS = 'GET_MY_PAYMENT_STATUS_SUCCESS';
export const GET_MY_PAYMENT_STATUS_FAIL = 'GET_MY_PAYMENT_STATUS_FAIL';




// ==================== SYSTEM ADMIN USER MANAGEMENT CONSTANTS ====================
export const SYSTEM_ADMIN_GET_ALL_USERS_REQUEST = 'SYSTEM_ADMIN_GET_ALL_USERS_REQUEST';
export const SYSTEM_ADMIN_GET_ALL_USERS_SUCCESS = 'SYSTEM_ADMIN_GET_ALL_USERS_SUCCESS';
export const SYSTEM_ADMIN_GET_ALL_USERS_FAIL = 'SYSTEM_ADMIN_GET_ALL_USERS_FAIL';

export const SYSTEM_ADMIN_DELETE_USER_REQUEST = 'SYSTEM_ADMIN_DELETE_USER_REQUEST';
export const SYSTEM_ADMIN_DELETE_USER_SUCCESS = 'SYSTEM_ADMIN_DELETE_USER_SUCCESS';
export const SYSTEM_ADMIN_DELETE_USER_FAIL = 'SYSTEM_ADMIN_DELETE_USER_FAIL';
export const SYSTEM_ADMIN_DELETE_USER_RESET = 'SYSTEM_ADMIN_DELETE_USER_RESET';

// ==================== COMMON CONSTANTS ====================
export const CLEAR_ERRORS = 'CLEAR_ERRORS';